added list command filter by side
packwiz/packwiz pull request #256
Opened 2023-09-12 05:29 UTC by 3AM-Developer

This is my first OS commit!
This should close issue #245 
I was looking for previous examples of this in the code base and I saw

2023-09-12 18:49 UTC, comp500 requested changes
Thanks for the PR! Looks good, just had a suggestion to improve the UX a bit.

2023-09-12 18:49 UTC, comp500 commented on cmd/list.go
> +				fmt.Println("Invalid side!")
Could you list the possible options the user has? e.g. `Invalid side "front", must be one of client, server, or both (default)`

2023-09-12 19:50 UTC, 3AM-Developer commented
Should I include this change to the Export command for Curseforge?

Currently it looks like this:
```
side := viper.GetString("curseforge.export.side")
if len(side) == 0 || (side != core.UniversalSide && side != core.ServerSide && side != core.ClientSide) {
	fmt.Println("Invalid side!")
	os.Exit(1)
}
```

2023-09-16 02:27 UTC, comp500 commented on cmd/list.go
> +				if len(side) == 0 || (mod.Side == side || mod.Side == core.EmptySide || mod.Side == core.UniversalSide || side == core.UniversalSide) {
No need for the len check here - the previous if already validates that the side is one of both/server/client

2023-09-16 02:27 UTC, comp500 commented on curseforge/export.go
> +		// cobra/viper ensures this value is set if the flag is used. Maybe remove the len Check?
Yeah you can remove the len check here as well - the latter checks already handle the case where the string is empty, and it's very unlikely that a user would manage to set the flag to `""`

2023-09-16 03:40 UTC, JaegyuDev commented
Should be good to go I believe!

2023-09-16 03:56 UTC, JaegyuDev commented
Quick question: in the future if I push code that has a minor issue like leaving a comment in, should I do 2 commits like I just did, or is there a better/preferred way of fixing something like that?

2023-09-16 16:22 UTC, comp500 commented
Making 2 commits is usually easiest, you can amend commits but if you've already pushed you'd need to do a force push to overwrite the existing commit. I usually squash PRs into a single commit so it doesn't make a difference once merged.

2023-09-16 16:25 UTC, comp500 approved these changes

2023-09-16 16:26 UTC, merged